- name: Create partitions2
  hosts: all
  become: true
  tasks:

    - name: gpt
      ansible.builtin.command: parted /dev/sda mklabel gpt

    - name: make primary "fat32"
      ansible.builtin.command: parted /dev/sda mkpart primary fat32 1MiB 1024MiB

    - name: "boot"
      ansible.builtin.command: parted /dev/sda set 1 boot on

    - name: "esp"
      ansible.builtin.command: parted /dev/sda set 1 esp on

    - name: "mkfs.fat"
      ansible.builtin.command: mkfs.fat -F32 /dev/sda1

    - name: part ext4
      ansible.builtin.command: parted /dev/sda mkpart primary ext4 1025MiB 57GiB

    - name: "mkfs.ext4"
      ansible.builtin.command: mkfs.ext4 /dev/sda2

    - name: mount /mnt
      ansible.builtin.command: mount /dev/sda2 /mnt

    - name: /mnt/boot
      ansible.builtin.command: mkdir -p /mnt/boot

    - name: /mnt/boot chmod 
      ansible.builtin.command: chmod 755 /mnt/boot

    - name: mount sda1
      ansible.builtin.command: mount /dev/sda1 /mnt/boot