---
- name: Install packages
  hosts: all
  vars:
    dotfiles_dir: "dotfiles"
    ansible_become_password: "arch"
  become: true
  tasks:  

# note that none of the packages under are required for running arch. modification can be made without breaking anything
# if GUI needs to be installed for example gnome just add it to one of the lists below and add gdm.service to start on start up. not guaranteed to work automatically since gnome likes to ask what to install.

    - name: Install packages 1
      ansible.builtin.pacman:
        name:
          - neovim
          - vim
          - firefox
          - curl
          - wget
          - jq
          - git
        state: present

    - name: Install packages 2
      ansible.builtin.pacman:
        name:
          - base-devel
          - wezterm
          - ttf-jetbrains-mono-nerd
          - spice-vdagent
          - docker
          - docker-compose
        state: present

    - name: Install packages 3
      ansible.builtin.pacman:
        name:
          - mesa
          - nmap
          - wireshark-qt
          - radamsa
          - afl
          - python-pycryptodome
        state: present

    - name: Enable system services
      ansible.builtin.systemd:
        name: docker
        enabled: yes

    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Ensure wireshark group exists
      ansible.builtin.group:
        name: wireshark
        state: present

    - name: Add arch user to groups
      ansible.builtin.user:
        name: arch
        groups: docker,wireshark
        append: yes