---
- name: Install packages
  hosts: all
  vars:
    dotfiles_dir: "dotfiles"
    ansible_become_password: "arch"
  become: true
  tasks:

# installs zsh for user and adds it as the default shell

  - name: Update system
    ansible.builtin.pacman:
      update_cache: true
      upgrade: true

  - name: Add BlackArch repository
    ansible.builtin.shell:
      echo "[blackarch]" >> /etc/pacman.conf
      echo bash -c 'echo -e "[blackarch]\nServer = https://blackarch.mirror.evilcorp.xyz/blackarch/\$repo/os/\$arch" >> /etc/pacman.conf'
      pacman -Syy
      pacman-key --init
      pacman-key --populate blackarch
      pacman -Syu --noconfirm

  - name: zsh
    ansible.builtin.pacman:
      name:
        - zsh
      state: present

  - name: Create .zshrc for user
    ansible.builtin.file:
      path: /home/arch/.zshrc
      state: touch
      owner: arch
      group: arch
      mode: '0644'

  - name: Change shell to zsh
    ansible.builtin.user:
      name: arch
      shell: /bin/zsh

  - name: Append zsh extensions to .zshrc
    ansible.builtin.command: /bin/bash -c 'su - arch -c "cat /dotfiles/zsh_extensions.zsh >> /home/arch/.zshrc"'

  - name: Clear pacman cache
    ansible.builtin.command: pacman -Scc --noconfirm