---
- name: Install packages
  hosts: all
  vars:
    dotfiles_dir: "dotfiles"
    ansible_become_password: "arch"
  become: true
  tasks:

# installs virtualbox and makes it functional. Can be added if needed in the future

    - name: Install VirtualBox
      ansible.builtin.pacman:
        name:
          - virtualbox
          - virtualbox-host-modules-arch
        state: present

    - name: Install VirtualBox Guest Utils
      ansible.builtin.pacman:
        name: virtualbox-guest-utils
        state: present

    - name: Enable VirtualBox service (only on x86_64)
      ansible.builtin.systemd:
        name: vboxservice
        enabled: yes
      when: ansible_architecture == "x86_64"