---
- name: Set time
  hosts: all
  vars:
      ansible_become_password: "arch"
  become: true
  tasks:
      - name: Set timezone to Europe/Helsinki
        file:
            src: /usr/share/zoneinfo/Europe/Helsinki
            dest: /etc/localtime
            state: link

      - name: Sync hardware clock
        ansible.builtin.command: hwclock --systohc

      - name: Enable and start systemd-timesyncd for time synchronization
        systemd:
            name: systemd-timesyncd
            enabled: yes
            state: started
